# Generated by Django 2.2.13 on 2022-11-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('alloted_team_ids', models.BigIntegerField()),
                ('branch', models.CharField(max_length=200)),
                ('semester', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('codechefID', models.CharField(max_length=100)),
                ('codeforcesID', models.CharField(max_length=100)),
                ('leetcodeID', models.CharField(max_length=100)),
                ('gfgID', models.CharField(max_length=100)),
                ('hackerrankID', models.CharField(max_length=100)),
                ('linkedinID', models.CharField(max_length=100)),
                ('score', models.BigIntegerField()),
                ('total_q', models.BigIntegerField()),
            ],
        ),
    ]
