# Generated by Django 4.0.3 on 2022-11-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('team_id', models.BigIntegerField()),
                ('branch', models.CharField(max_length=200)),
                ('semester', models.BigIntegerField()),
                ('phone_number', models.BigIntegerField()),
                ('codechefID', models.TextField()),
                ('codeforcesID', models.TextField()),
                ('leetcodeID', models.TextField()),
                ('gfgID', models.TextField()),
                ('hackerrankID', models.TextField()),
                ('linkedinID', models.TextField()),
                ('score', models.BigIntegerField()),
                ('solved_q', models.BigIntegerField()),
                ('alloted_mentor_id', models.BigIntegerField()),
                ('rank', models.BigIntegerField()),
            ],
        ),
    ]
