# Generated by Django 4.1.3 on 2022-12-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='codechefID',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='codeforcesID',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='gfgID',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='hackerrankID',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='leetcodeID',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='linkedinID',
            field=models.URLField(max_length=100),
        ),
    ]
