# Generated by Django 4.1.3 on 2022-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_mentor_alloted_team_ids_alter_mentor_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='branch',
            field=models.CharField(choices=[('1', 'CSE'), ('2', 'IT'), ('3', 'ECE'), ('4', 'ELEC'), ('5', 'MECH'), ('6', 'CHEM'), ('7', 'CIVIL'), ('8', 'META'), ('9', 'MIN'), ('10', 'BIOMED'), ('11', 'BIOTECH'), ('12', 'MCA')], max_length=10),
        ),
    ]
