# Generated by Django 4.1.3 on 2022-12-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_mentor_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
