# Generated by Django 2.2.13 on 2022-11-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('EASY', '1'), ('MEDIUM', '2'), ('HARD', '3')], default='EASY', max_length=20)),
                ('mentor_id', models.CharField(max_length=200)),
                ('codechefLink', models.CharField(max_length=200)),
                ('codeforcesLink', models.CharField(max_length=200)),
                ('gfgLink', models.CharField(max_length=200)),
                ('leetcodeLink', models.CharField(max_length=200)),
                ('hacekrrankLink', models.CharField(max_length=200)),
                ('alloted_at', models.CharField(max_length=200)),
                ('global_check', models.DateTimeField()),
            ],
        ),
    ]
