# Generated by Django 4.1 on 2022-11-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
# Generated by Django 4.1.3 on 2022-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('codechefLink', models.CharField(max_length=200)),
                ('codeforcesLink', models.CharField(max_length=200)),
                ('gfgLink', models.CharField(max_length=200)),
                ('leetcodeLink', models.CharField(max_length=200)),
                ('hackerrankLink', models.CharField(max_length=200)),
                ('global_check', models.BooleanField(default=False)),
                ('level', models.CharField(max_length=20)),
                ('mentor_id', models.IntegerField()),
                ('alloted_at', models.DateTimeField()),
            ],
        ),
    ]
