# Generated by Django 4.1.3 on 2022-11-08 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='codechefLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='codeforcesLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='gfgLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='hackerrankLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='leetcodeLink',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.topic'),
        ),
    ]
