# Generated by Django 4.1.3 on 2022-11-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_global_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mentor_id',
        ),
    ]
