# Generated by Django 4.1.3 on 2022-12-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_mentor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_level', models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6)),
                ('solved_at', models.DateTimeField()),
                ('solved_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.topic')),
            ],
        ),
    ]
